/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Link = {
  _type: "link";
  linkType?: "href" | "news";
  href?: string;
  news?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "news";
  };
  openInNewTab?: boolean;
};

export type CallToAction = {
  _type: "callToAction";
  heading: string;
  text?: string;
  buttonText?: string;
  link?: Link;
};

export type InfoSection = {
  _type: "infoSection";
  heading?: string;
  subheading?: string;
  content?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    linkType?: "href" | "news";
    href?: string;
    news?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "news";
    };
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Leadership = {
  _id: string;
  _type: "leadership";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  position?: string;
  role: "prezidentas" | "viceprezidentas" | "prezidiumoNarys" | "prezidiumoGarbesNarys";
  photo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  phone?: string;
  email?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Member = {
  _id: string;
  _type: "member";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ValdymasSettings = {
  _id: string;
  _type: "valdymasSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  presidentMessage?: BlockContent;
};

export type Veikla = {
  _id: string;
  _type: "veikla";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  misija: string;
  vizija: string;
  strategicDirections?: Array<{
    title: string;
    _key: string;
  }>;
  ataskaitos?: Array<{
    period: string;
    file: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
    _key: string;
  }>;
};

export type Partneriai = {
  _id: string;
  _type: "partneriai";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  partnersCooperate?: Array<{
    title: string;
    extra?: string;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "partner";
    _key: string;
  }>;
  partnersAgreements?: Array<{
    title: string;
    extra?: string;
    logo?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "agreement";
    _key: string;
  }>;
};

export type Istorija = {
  _id: string;
  _type: "istorija";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  turnover?: string;
  ourHistory?: BlockContent;
  services?: Array<{
    title: string;
    description?: string;
    _type: "service";
    _key: string;
  }>;
  pastPresidents?: Array<{
    name: string;
    startYear: number;
    endYear?: number;
    _type: "pastPresident";
    _key: string;
  }>;
};

export type MembershipInfo = {
  _id: string;
  _type: "membershipInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  whyJoinText?: BlockContent;
  benefitsText?: Array<{
    title: string;
    description1?: string;
    description2?: string;
    description3?: string;
    description4?: string;
    _type: "benefitItem";
    _key: string;
  }>;
  requiredDocuments?: Array<{
    title: string;
    description?: string;
    file?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
    _type: "documentItem";
    _key: string;
  }>;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  type: "naujiena" | "renginys";
  isFeatured?: boolean;
  content?: BlockContent;
  coverImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt: string;
  eventStartDate?: string;
  eventEndDate?: string;
  organizers?: Array<string>;
  location?: string;
  googleMapsLocation?: string;
  entrance?: string;
  registrationUrl?: string;
  timeSlots?: Array<string>;
  program?: Array<{
    date: string;
    title: string;
    time?: string;
    description?: string;
    _key: string;
  }>;
  documents?: Array<{
    title: string;
    file: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
    _key: string;
  }>;
  additionalInfo?: Array<{
    title: string;
    description?: string;
    items?: Array<string>;
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Istatai = {
  _id: string;
  _type: "istatai";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  statutesFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  ethicsFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
};

export type ContactInfo = {
  _id: string;
  _type: "contactInfo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  address?: string;
  phone?: string;
  email?: string;
  googleAddress?: string;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<{
    _key: string;
  } & SanityAssistInstructionTask>;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<{
    _key: string;
  } & SanityAssistSchemaTypeField>;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | {
    _key: string;
  } & SanityAssistInstructionFieldRef | {
    _key: string;
  } & SanityAssistInstructionContext | {
    _key: string;
  } & SanityAssistInstructionUserInput>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<{
    _key: string;
  } & SanityAssistOutputField | {
    _key: string;
  } & SanityAssistOutputType>;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<{
    _key: string;
  } & SanityAssistInstruction>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Link | CallToAction | InfoSection | BlockContent | Leadership | SanityImageCrop | SanityImageHotspot | Member | ValdymasSettings | Veikla | Partneriai | Istorija | MembershipInfo | News | Slug | Istatai | ContactInfo | SanityAssistInstructionTask | SanityAssistTaskStatus | SanityAssistSchemaTypeAnnotations | SanityAssistOutputType | SanityAssistOutputField | SanityAssistInstructionContext | AssistInstructionContext | SanityAssistInstructionUserInput | SanityAssistInstructionPrompt | SanityAssistInstructionFieldRef | SanityAssistInstruction | SanityAssistSchemaTypeField | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: apieKkpdaQuery
// Query: *[_id == "apieKkpda"][0] {    kasEsame,    kaAtstovaujame,    musuMisija,    musuVizija,    misija,    vizija,    strateginesVeiklosKryptys[] {      _key,      title    },    kurEiname,    "kurEinamePaveikslasUrl": kurEinamePaveikslas.asset->url,    darboVietos,    apyvarta,    organizacijos[] {      pavadinimas,      aprasymas,      "logoUrl": logo.asset->url    }  }
export type ApieKkpdaQueryResult = {
  kasEsame: null;
  kaAtstovaujame: null;
  musuMisija: null;
  musuVizija: null;
  misija: null;
  vizija: null;
  strateginesVeiklosKryptys: null;
  kurEiname: null;
  kurEinamePaveikslasUrl: null;
  darboVietos: null;
  apyvarta: null;
  organizacijos: null;
} | {
  kasEsame: null;
  kaAtstovaujame: null;
  musuMisija: null;
  musuVizija: null;
  misija: string;
  vizija: string;
  strateginesVeiklosKryptys: null;
  kurEiname: null;
  kurEinamePaveikslasUrl: null;
  darboVietos: null;
  apyvarta: null;
  organizacijos: null;
} | null;
// Variable: leadershipQuery
// Query: *[_type == "leadership"] | order(role asc, name asc) {    _id,    name,    position,    role,    "photo": photo{      asset->{        _id,        url      }    },    phone,    email  }
export type LeadershipQueryResult = Array<{
  _id: string;
  name: string;
  position: string | null;
  role: "prezidentas" | "prezidiumoGarbesNarys" | "prezidiumoNarys" | "viceprezidentas";
  photo: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  };
  phone: string | null;
  email: string | null;
}>;
// Variable: newsQuery
// Query: *[_type == "news"] | order(publishedAt desc) [0...5] {    _id,    title,    slug,    type,    isFeatured,    content,    "coverImage": coverImage{      asset->{        _id,        url      }    },    publishedAt  }
export type NewsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  type: "naujiena" | "renginys";
  isFeatured: boolean | null;
  content: BlockContent | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  publishedAt: string;
}>;
// Variable: allNewsQuery
// Query: *[_type == "news"] | order(isFeatured desc, publishedAt desc) {    _id,    title,    slug,    type,    isFeatured,    content,    "coverImage": coverImage{      asset->{        _id,        url      }    },    publishedAt,    eventStartDate,    eventEndDate,    organizers,    location,    googleMapsLocation  }
export type AllNewsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  type: "naujiena" | "renginys";
  isFeatured: boolean | null;
  content: BlockContent | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  publishedAt: string;
  eventStartDate: string | null;
  eventEndDate: string | null;
  organizers: Array<string> | null;
  location: string | null;
  googleMapsLocation: string | null;
}>;
// Variable: recentNewsQuery
// Query: *[_type == "news"] | order(publishedAt desc) [0...5] {    _id,    title,    slug,    type,    publishedAt  }
export type RecentNewsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  type: "naujiena" | "renginys";
  publishedAt: string;
}>;
// Variable: singleNewsQuery
// Query: *[_type == "news" && slug.current == $slug][0] {    _id,    title,    slug,    type,    content,    "coverImage": coverImage{      asset->{        _id,        url      }    },    publishedAt,    eventStartDate,    eventEndDate,    organizers,    location,    googleMapsLocation,    entrance,    registrationUrl,    timeSlots,    program,    "documents": documents[]{      title,      "file": file.asset->{        _id,        url,        originalFilename,        size      }    },    additionalInfo  }
export type SingleNewsQueryResult = {
  _id: string;
  title: string;
  slug: Slug;
  type: "naujiena" | "renginys";
  content: BlockContent | null;
  coverImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  publishedAt: string;
  eventStartDate: string | null;
  eventEndDate: string | null;
  organizers: Array<string> | null;
  location: string | null;
  googleMapsLocation: string | null;
  entrance: string | null;
  registrationUrl: string | null;
  timeSlots: Array<string> | null;
  program: Array<{
    date: string;
    title: string;
    time?: string;
    description?: string;
    _key: string;
  }> | null;
  documents: Array<{
    title: string;
    file: {
      _id: string;
      url: string | null;
      originalFilename: string | null;
      size: number | null;
    } | null;
  }> | null;
  additionalInfo: Array<{
    title: string;
    description?: string;
    items?: Array<string>;
    _key: string;
  }> | null;
} | null;
// Variable: istorijaQuery
// Query: *[_id == "istorija"][0] {    ourHistory,    "pastPresidents": pastPresidents[] {      _key,      name,      startYear,      endYear    }  }
export type IstorijaQueryResult = {
  ourHistory: null;
  pastPresidents: null;
} | {
  ourHistory: BlockContent | null;
  pastPresidents: Array<{
    _key: string;
    name: string;
    startYear: number;
    endYear: number | null;
  }> | null;
} | null;
// Variable: valdymasSettingsQuery
// Query: *[_id == "valdymasSettings"][0] {    presidentMessage  }
export type ValdymasSettingsQueryResult = {
  presidentMessage: null;
} | {
  presidentMessage: BlockContent | null;
} | null;
// Variable: membersCountQuery
// Query: count(*[_type == "member"])
export type MembersCountQueryResult = number;
// Variable: membersQuery
// Query: *[_type == "member"] | order(lower(company) asc) {    _id,    company,    "logo": logo{      asset->{        _id,        url      }    }  }
export type MembersQueryResult = Array<{
  _id: string;
  company: string;
  logo: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: partnersQuery
// Query: *[_id == "partneriai"][0] {    "cooperate": partnersCooperate[] {      _key,      title,      "logo": logo.asset->url,      extra    },    "agreements": partnersAgreements[] {      _key,      title,      extra    }  }
export type PartnersQueryResult = {
  cooperate: null;
  agreements: null;
} | {
  cooperate: Array<{
    _key: string;
    title: string;
    logo: string | null;
    extra: string | null;
  }> | null;
  agreements: Array<{
    _key: string;
    title: string;
    extra: string | null;
  }> | null;
} | null;
// Variable: contactInfoQuery
// Query: *[_type == "contactInfo"][0] {    address,    phone,    email,    googleAddress  }
export type ContactInfoQueryResult = {
  address: string | null;
  phone: string | null;
  email: string | null;
  googleAddress: string | null;
} | null;
// Variable: legalDocumentsQuery
// Query: *[_type == "istatai"][0] {    introTitle,    introText,    "introImageUrl": introImage.asset->url,    "statutesUrl": statutesFile.asset->url,    "statutesName": statutesFile.asset->originalFilename,    ethicsTitle,    ethicsDescription,    ethicsValuesIntro,    ethicsValues[] {      title    },    ethicsNotes[] {      text,      isItalic    },    "ethicsUrl": ethicsFile.asset->url,    "ethicsName": ethicsFile.asset->originalFilename,    privacyTitle,    privacyDescription,    "privacyUrl": privacyFile.asset->url,    "privacyName": privacyFile.asset->originalFilename  }
export type LegalDocumentsQueryResult = {
  introTitle: null;
  introText: null;
  introImageUrl: null;
  statutesUrl: string | null;
  statutesName: string | null;
  ethicsTitle: null;
  ethicsDescription: null;
  ethicsValuesIntro: null;
  ethicsValues: null;
  ethicsNotes: null;
  ethicsUrl: string | null;
  ethicsName: string | null;
  privacyTitle: null;
  privacyDescription: null;
  privacyUrl: null;
  privacyName: null;
} | null;
// Variable: eventsListQuery
// Query: *[_type == "event" &&    (!defined($from) || $from == null || coalesce(startAt, dateTime(date)) >= dateTime($from)) &&    (!defined($to) || $to == null || coalesce(startAt, dateTime(date)) <= dateTime($to))  ] | order(coalesce(startAt, dateTime(date)) desc) {    _id,    title,    slug,    date,    startAt,    endAt,    time,    location,    organizers,    excerpt,    "plainContent": pt::text(content),    "cover": images[0]{ asset->{ _id, url } }  }
export type EventsListQueryResult = Array<never>;
// Variable: singleEventQuery
// Query: *[_type == "event" && slug.current == $slug][0] {    _id,    title,    slug,    date,    startAt,    endAt,    time,    location,    locationLat,    locationLng,    organizers,    excerpt,    content,    images[]{ asset->{ _id, url } }  }
export type SingleEventQueryResult = null;
// Variable: membershipInfoQuery
// Query: *[_id == "membershipInfo"][0] {    whyJoinText,    whoCanJoinTitle,    whoCanJoinText,    whoCanJoinHighlights[] {      _key,      title,      description    },    requiredDocuments[] {      _key,      title,      description,      "fileUrl": file.asset->url,      "fileName": file.asset->originalFilename,      buttonText    },    ctaTitle,    ctaText  }
export type MembershipInfoQueryResult = {
  whyJoinText: null;
  whoCanJoinTitle: null;
  whoCanJoinText: null;
  whoCanJoinHighlights: null;
  requiredDocuments: null;
  ctaTitle: null;
  ctaText: null;
} | {
  whyJoinText: BlockContent | null;
  whoCanJoinTitle: null;
  whoCanJoinText: null;
  whoCanJoinHighlights: null;
  requiredDocuments: Array<{
    _key: string;
    title: string;
    description: string | null;
    fileUrl: string | null;
    fileName: string | null;
    buttonText: null;
  }> | null;
  ctaTitle: null;
  ctaText: null;
} | null;
// Variable: narystesNaudosQuery
// Query: *[_id == "narystesNaudos"][0] {    benefitsText[] {      _key,      title,      description1,      description2,      description3,      description4    }  }
export type NarystesNaudosQueryResult = {
  benefitsText: null;
} | {
  benefitsText: Array<{
    _key: string;
    title: string;
    description1: string | null;
    description2: string | null;
    description3: string | null;
    description4: string | null;
  }> | null;
} | null;
// Variable: atstovavimasQuery
// Query: *[_id == "atstovavimas"][0] {    nationalActivities[] {      _key,      title,      description    },    regionalActivities[] {      _key,      title,      description    }  }
export type AtstovavimasQueryResult = {
  nationalActivities: null;
  regionalActivities: null;
} | null;
// Variable: veiklosAtaskaitosQuery
// Query: *[_id == "veiklosAtaskaitos"][0] {    "ataskaitos": ataskaitos[] {      _key,      period,      "fileUrl": file.asset->url,      "fileName": file.asset->originalFilename    }  }
export type VeiklosAtaskaitosQueryResult = {
  ataskaitos: null;
} | {
  ataskaitos: Array<{
    _key: string;
    period: string;
    fileUrl: string | null;
    fileName: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_id == \"apieKkpda\"][0] {\n    kasEsame,\n    kaAtstovaujame,\n    musuMisija,\n    musuVizija,\n    misija,\n    vizija,\n    strateginesVeiklosKryptys[] {\n      _key,\n      title\n    },\n    kurEiname,\n    \"kurEinamePaveikslasUrl\": kurEinamePaveikslas.asset->url,\n    darboVietos,\n    apyvarta,\n    organizacijos[] {\n      pavadinimas,\n      aprasymas,\n      \"logoUrl\": logo.asset->url\n    }\n  }\n": ApieKkpdaQueryResult;
    "\n  *[_type == \"leadership\"] | order(role asc, name asc) {\n    _id,\n    name,\n    position,\n    role,\n    \"photo\": photo{\n      asset->{\n        _id,\n        url\n      }\n    },\n    phone,\n    email\n  }\n": LeadershipQueryResult;
    "\n  *[_type == \"news\"] | order(publishedAt desc) [0...5] {\n    _id,\n    title,\n    slug,\n    type,\n    isFeatured,\n    content,\n    \"coverImage\": coverImage{\n      asset->{\n        _id,\n        url\n      }\n    },\n    publishedAt\n  }\n": NewsQueryResult;
    "\n  *[_type == \"news\"] | order(isFeatured desc, publishedAt desc) {\n    _id,\n    title,\n    slug,\n    type,\n    isFeatured,\n    content,\n    \"coverImage\": coverImage{\n      asset->{\n        _id,\n        url\n      }\n    },\n    publishedAt,\n    eventStartDate,\n    eventEndDate,\n    organizers,\n    location,\n    googleMapsLocation\n  }\n": AllNewsQueryResult;
    "\n  *[_type == \"news\"] | order(publishedAt desc) [0...5] {\n    _id,\n    title,\n    slug,\n    type,\n    publishedAt\n  }\n": RecentNewsQueryResult;
    "\n  *[_type == \"news\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    type,\n    content,\n    \"coverImage\": coverImage{\n      asset->{\n        _id,\n        url\n      }\n    },\n    publishedAt,\n    eventStartDate,\n    eventEndDate,\n    organizers,\n    location,\n    googleMapsLocation,\n    entrance,\n    registrationUrl,\n    timeSlots,\n    program,\n    \"documents\": documents[]{\n      title,\n      \"file\": file.asset->{\n        _id,\n        url,\n        originalFilename,\n        size\n      }\n    },\n    additionalInfo\n  }\n": SingleNewsQueryResult;
    "\n  *[_id == \"istorija\"][0] {\n    ourHistory,\n    \"pastPresidents\": pastPresidents[] {\n      _key,\n      name,\n      startYear,\n      endYear\n    }\n  }\n": IstorijaQueryResult;
    "\n  *[_id == \"valdymasSettings\"][0] {\n    presidentMessage\n  }\n": ValdymasSettingsQueryResult;
    "\n  count(*[_type == \"member\"])\n": MembersCountQueryResult;
    "\n  *[_type == \"member\"] | order(lower(company) asc) {\n    _id,\n    company,\n    \"logo\": logo{\n      asset->{\n        _id,\n        url\n      }\n    }\n  }\n": MembersQueryResult;
    "\n  *[_id == \"partneriai\"][0] {\n    \"cooperate\": partnersCooperate[] {\n      _key,\n      title,\n      \"logo\": logo.asset->url,\n      extra\n    },\n    \"agreements\": partnersAgreements[] {\n      _key,\n      title,\n      extra\n    }\n  }\n": PartnersQueryResult;
    "\n  *[_type == \"contactInfo\"][0] {\n    address,\n    phone,\n    email,\n    googleAddress\n  }\n": ContactInfoQueryResult;
    "\n  *[_type == \"istatai\"][0] {\n    introTitle,\n    introText,\n    \"introImageUrl\": introImage.asset->url,\n    \"statutesUrl\": statutesFile.asset->url,\n    \"statutesName\": statutesFile.asset->originalFilename,\n    ethicsTitle,\n    ethicsDescription,\n    ethicsValuesIntro,\n    ethicsValues[] {\n      title\n    },\n    ethicsNotes[] {\n      text,\n      isItalic\n    },\n    \"ethicsUrl\": ethicsFile.asset->url,\n    \"ethicsName\": ethicsFile.asset->originalFilename,\n    privacyTitle,\n    privacyDescription,\n    \"privacyUrl\": privacyFile.asset->url,\n    \"privacyName\": privacyFile.asset->originalFilename\n  }\n": LegalDocumentsQueryResult;
    "\n  *[_type == \"event\" &&\n    (!defined($from) || $from == null || coalesce(startAt, dateTime(date)) >= dateTime($from)) &&\n    (!defined($to) || $to == null || coalesce(startAt, dateTime(date)) <= dateTime($to))\n  ] | order(coalesce(startAt, dateTime(date)) desc) {\n    _id,\n    title,\n    slug,\n    date,\n    startAt,\n    endAt,\n    time,\n    location,\n    organizers,\n    excerpt,\n    \"plainContent\": pt::text(content),\n    \"cover\": images[0]{ asset->{ _id, url } }\n  }\n": EventsListQueryResult;
    "\n  *[_type == \"event\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    date,\n    startAt,\n    endAt,\n    time,\n    location,\n    locationLat,\n    locationLng,\n    organizers,\n    excerpt,\n    content,\n    images[]{ asset->{ _id, url } }\n  }\n": SingleEventQueryResult;
    "\n  *[_id == \"membershipInfo\"][0] {\n    whyJoinText,\n    whoCanJoinTitle,\n    whoCanJoinText,\n    whoCanJoinHighlights[] {\n      _key,\n      title,\n      description\n    },\n    requiredDocuments[] {\n      _key,\n      title,\n      description,\n      \"fileUrl\": file.asset->url,\n      \"fileName\": file.asset->originalFilename,\n      buttonText\n    },\n    ctaTitle,\n    ctaText\n  }\n": MembershipInfoQueryResult;
    "\n  *[_id == \"narystesNaudos\"][0] {\n    benefitsText[] {\n      _key,\n      title,\n      description1,\n      description2,\n      description3,\n      description4\n    }\n  }\n": NarystesNaudosQueryResult;
    "\n  *[_id == \"atstovavimas\"][0] {\n    nationalActivities[] {\n      _key,\n      title,\n      description\n    },\n    regionalActivities[] {\n      _key,\n      title,\n      description\n    }\n  }\n": AtstovavimasQueryResult;
    "\n  *[_id == \"veiklosAtaskaitos\"][0] {\n    \"ataskaitos\": ataskaitos[] {\n      _key,\n      period,\n      \"fileUrl\": file.asset->url,\n      \"fileName\": file.asset->originalFilename\n    }\n  }\n": VeiklosAtaskaitosQueryResult;
  }
}
